name: Test

on:
  # push: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install cookiecutter
        run: |
          python -m pip install cookiecutter
      - name: Test build
        run: |
          bash ./scripts/test.sh
